### ISSUE TITLE
Mixed case variables or Variable Names Beginning With Capital Letters?

### ISSUE THREAD

**Issue by razorsedge** [fiddyspence/puppetlint-variablecase#1]
Shouldn't this module check for *initial* uppercase letter and not mixed case?  I see that Future Parser is documented as against mixed case, although code passes rspec tests just fine.  But Puppet 4 actually documents initial upppercase.

References:
[Deprecated Language Features](https://docs.puppetlabs.com/puppet/3.7/reference/deprecated_language.html#variable-names-beginning-with-capital-letters)
[Experimental Features: The Future Parser](https://docs.puppetlabs.com/puppet/latest/reference/experiments_future.html#capitalized-variable-names-not-allowed)

**Comment by fiddyspence** [comment]
I think there was a reason I originally had it as camel and mixed case (at that point i think the future parser didn't like either).

**Comment by fiddyspence** [comment]
Well, either reality or the docs are out of line - this from your second link:

Capitalized Variable Names Not Allowed

Variable names may not contain capital letters. They are limited to lowercase letters, numbers, and underscores.

**Comment by razorsedge** [comment]
The thing is, now that Puppet 4 is available, the future parser is no longer relevant.  I would rather see tests against what P4 requires and not the hodgepodge that is^H^Hwas future parser.

**Comment by fiddyspence** [comment]
Back to this.  It's a linking check, not a syntax check, so it's entirely stylistic.  Because it's stylistic, and all it does is enforce a rule of no upcase letters in variable names (because ohmygod mIXedCasE - I, stylistically do not want mixed case in my code base), so I'm going to leave this check as is.
